"""empty message

Revision ID: 77cd2bc7dbc7
Revises: 
Create Date: 2024-09-28 12:39:04.313453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77cd2bc7dbc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('unidades_peso', sa.String(length=250), nullable=False),
    sa.Column('unidades_altura', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('clima', sa.String(length=250), nullable=False),
    sa.Column('poblacion', sa.Integer(), nullable=False),
    sa.Column('periodo_rotacion', sa.Integer(), nullable=False),
    sa.Column('superficie_agua', sa.Integer(), nullable=False),
    sa.Column('diametro', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('lastname', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_date'), ['date'], unique=False)

    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('favorite_personaje', sa.Integer(), nullable=True),
    sa.Column('favorite_planeta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_personaje'], ['personaje.id'], ),
    sa.ForeignKeyConstraint(['favorite_planeta'], ['planeta.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_date'))

    op.drop_table('user')
    op.drop_table('planeta')
    op.drop_table('personaje')
    # ### end Alembic commands ###
